//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elegant_flower_shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Customer
    {
        public int customer_id { get; set; }
        [Required(ErrorMessage = "Name cannot be empty")]
        [Display(Name = "User Name")]
        public string customerName { get; set; }
        [Required(ErrorMessage = "Phone Number cannot be empty")]
        [DataType(DataType.PhoneNumber)]
        [MinLength(11, ErrorMessage = "Phone Number must be atleast 11 digits")]
        [Display(Name = "PhoneNumber")]
        public string customerPhone { get; set; }
        [Required(ErrorMessage = "Email cannot be empty")]
        [EmailAddress(ErrorMessage = "Please enter a correct email")]
        public string customerEmail { get; set; }
        [Required(ErrorMessage = "Password cannot be empty")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Password must be atleast 6 characters long")]
        [Display(Name = "Password")]
        public string customerPassword { get; set; }
    }
}
